### ISSUE TITLE
Connection fails due to certificate verification

### ISSUE THREAD

**Issue by Alexanderis** [arista-eosext/rphm#6]
Hi team,

Tool is no longer able to access switches and its spitting out the error in the attached screenshot.

![image](https://user-images.githubusercontent.com/18032132/27292052-0c2377d4-550a-11e7-8777-5b647b2ae8f5.png)
Setting the SSL context to unverified resolves this issue:
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by jerearista** [comment]
This is due to the fact that EOS eAPI uses self-signed certificates by default and newer versions of Python come with SSL certificate validation enforced by default.  The proper resolution is to install valid, trusted certificates on all devices.  If that is not desired, another option is to disable certificate validation within Python.  In this case, the data will still be encrypted but you have no assurance that you are communicating with a trusted device.

I have added a check that will detect a certificate validation failure, throw a warning, then retry the connection on the next cycle with certificate validation disabled.
